[package]
name = "babylon-btcstaking"
description = "BTC staking library in Rust"
version.workspace = true
edition.workspace = true


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin      = { workspace = true }
rust_decimal = { workspace = true }
hex          = { workspace = true }
schnorr_fun  = { workspace = true }
secp256kfun  = { workspace = true }
sha2         = { workspace = true }

[dev-dependencies]
babylon-proto = { workspace = true }
prost         = { workspace = true }
