[package]
name = "babylon-apis"
version.workspace = true
edition.workspace = true

[dependencies]
babylon-bitcoin = { path = "../bitcoin" }
cosmwasm-std    = { workspace = true }
cosmwasm-schema = { workspace = true }
hex             = { workspace = true }
thiserror       = { workspace = true }
