[package]
name = "babylon-bindings"
version = "0.4.0"
authors = ["Babylonchain <info@bylonchain.io>"]
edition = "2021"
description = "Bindings for CustomMsg for the Babylon blockchain"
repository = "https://github.com/babylonchain/babylon-contract"
homepage = "https://babylonchain.io"
license = "Apache-2.0"

[dependencies]
cosmwasm-std    = { workspace = true }
cosmwasm-schema = { workspace = true }