[package]
name = "babylon-bitcoin"
description = "A wrapper of the rust-bitcoin library"
version.workspace = true
edition.workspace = true

[dependencies]
bitcoin      = { workspace = true }
serde        = { workspace = true }
schemars     = { workspace = true }
cosmwasm-std = { workspace = true }

[dev-dependencies]
hex          = { workspace = true }
