[package]
name = "babylon-bitcoin"
description = "A wrapper of the rust-bitcoin library"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin      = { workspace = true }
serde        = { workspace = true }
schemars     = { workspace = true }
cosmwasm-std = { workspace = true }

[dev-dependencies]
hex          = { workspace = true }
