[package]
name = "test-utils"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
babylon-proto    = { path = "../proto" }
babylon-bitcoin  = { path = "../bitcoin" }
cargo_metadata   = { workspace = true }
hex              = { workspace = true }
prost            = { workspace = true }
serde            = { workspace = true }
serde_json       = { workspace = true }