[package]
name = "babylon-merkle"
description = "CometBFT compatible Merkle proofs"
version.workspace = true
edition.workspace = true

[dependencies]
cosmwasm-schema  = { workspace = true }
cosmwasm-std     = { workspace = true }

hex              = { workspace = true }
schemars         = { workspace = true }
sha2             = { workspace = true }
serde            = { workspace = true }
tendermint-proto = { workspace = true }
thiserror        = { workspace = true }

[dev-dependencies]
hex              = { workspace = true }
